# Generated by Django 5.1.2 on 2024-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedicalrecord',
            name='prescription',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
