# Generated by Django 5.1.2 on 2024-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0004_permissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedicalrecord',
            name='date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
