# Generated by Django 5.1.2 on 2024-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0007_permissionrequest_edit_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
