# Generated by Django 5.1.2 on 2024-11-28 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0008_permissionrequest_expiration_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissionrequest',
            unique_together={('doctor', 'medical_record')},
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='medical_record.medicalrecord'),
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='edit_permission',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='expiration_time',
        ),
    ]
