# Generated by Django 5.1.2 on 2024-11-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0010_permissionrequest_edit_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='edit_permission',
        ),
    ]
